# JMeter 结果文件格式配置
# 强制使用 CSV 格式，否则 -e 生成 HTML 报告会失败
jmeter.save.saveservice.output_format=csv
jmeter.save.saveservice.response_data=false
jmeter.save.saveservice.response_code=true
jmeter.save.saveservice.response_message=true
jmeter.save.saveservice.successful=true
jmeter.save.saveservice.label=true
jmeter.save.saveservice.thread_name=true
jmeter.save.saveservice.time_stamp=true
jmeter.save.saveservice.elapsed_time=true
jmeter.save.saveservice.latency=true
jmeter.save.saveservice.connect_time=true
jmeter.save.saveservice.bytes=true
jmeter.save.saveservice.sent_bytes=true
jmeter.save.saveservice.thread_counts=true
jmeter.save.saveservice.idle_time=true
jmeter.save.saveservice.assertion_results=true
jmeter.save.saveservice.subresults=true

# 中文乱码修复
saveservice.default_encoding=UTF-8

# 升级兼容
upgrade_properties=true
